package com.weilan.knowledge;
import android.app.*;import android.os.*;import android.content.*;import android.net.Uri;
import android.graphics.Color;import android.graphics.Typeface;import android.graphics.drawable.GradientDrawable;
import android.view.*;import android.view.inputmethod.InputMethodManager;import android.widget.*;
import android.speech.RecognizerIntent;import android.speech.tts.TextToSpeech;
import org.json.*;import java.io.*;import java.net.URLEncoder;import java.util.*;import java.util.concurrent.*;

/** Native UI with HTTPS API clients. The application does not embed a browser. */
public class MainActivity extends Activity {
 private SecureStore store;private ApiClient api;private FrameLayout frame;private LinearLayout root,body,composer,chat;
 private EditText input;private TextView status;private Icons send;private ScrollView conversation;
 private int thumbnailRequests=0;private final ExecutorService thumbnails=Executors.newFixedThreadPool(2);private final android.util.LruCache<String,android.graphics.Bitmap> thumbnailCache=new android.util.LruCache<String,android.graphics.Bitmap>(8*1024*1024){protected int sizeOf(String key,android.graphics.Bitmap bitmap){return bitmap.getByteCount();}};private View drawer;private final ExecutorService jobs=Executors.newFixedThreadPool(3);
 private String service="kb",page="chat",session="",agent="",title="新对话",recordId="",profile="";
 private JSONArray messages=new JSONArray(),history=new JSONArray();private boolean busy=false,work=false,speak=false,destroyed=false;
 private int generation=0;private TextToSpeech tts;private boolean ttsReady=false;private String downloadPath="",downloadProfile="";private JSONArray attachments=new JSONArray();
 private static final int PICK_TEXT=31,SAVE_FILE=32,VOICE=33,VPN_CONSENT=34,NOTIFY_CONSENT=35;
 private final Handler firewallHandler=new Handler(Looper.getMainLooper());
 private int dp(float n){return Math.round(n*getResources().getDisplayMetrics().density);}
 @Override public void onCreate(Bundle state){super.onCreate(state);
  try{store=new SecureStore(this);for(String key:new String[]{"kb_url","octop_url"}){String saved=store.get(key,"");String old="https://kb.example.com";if(saved.equals(old)||saved.startsWith(old+"/")){store.put(key,ApiClient.DEFAULT_KB+saved.substring(old.length()));String svc=key.equals("kb_url")?"kb":"octop";store.put(svc+"_token","");store.put(svc+"_identity","");store.put(svc+"_tenant","");}}api=new ApiClient(store);history=new JSONArray(store.get("history","[]"));service=store.get("last_service","kb");agent=store.get("octop_agent","");if(!Arrays.asList("kb","llm","octop").contains(service))service="kb";}
  catch(Exception e){new AlertDialog.Builder(this).setMessage("本机加密存储不可用，请检查设备后重试。").setPositiveButton("关闭",(d,w)->finish()).show();return;}
  getWindow().setStatusBarColor(Color.WHITE);getWindow().setNavigationBarColor(Color.WHITE);getWindow().getDecorView().setSystemUiVisibility(View.SYSTEM_UI_FLAG_LIGHT_STATUS_BAR|View.SYSTEM_UI_FLAG_LIGHT_NAVIGATION_BAR);
  // Credential editing screens and company documents should not be captured by other apps.
  if(getIntent().getBooleanExtra("open_firewall",false))page="firewall";
  tts=new TextToSpeech(this,result->{ttsReady=result==TextToSpeech.SUCCESS;if(ttsReady&&tts!=null)tts.setLanguage(Locale.SIMPLIFIED_CHINESE);});render();
 }
 private GradientDrawable bg(int color,int stroke,float radius){GradientDrawable d=new GradientDrawable();d.setColor(color);d.setCornerRadius(dp(radius));if(stroke!=0)d.setStroke(dp(1),stroke);return d;}
 private LinearLayout col(){LinearLayout l=new LinearLayout(this);l.setOrientation(1);return l;}
 private LinearLayout row(){LinearLayout l=new LinearLayout(this);l.setGravity(Gravity.CENTER_VERTICAL);return l;}
 private TextView text(String s,int size,int color){TextView v=new TextView(this);v.setText(s);v.setTextSize(size);v.setTextColor(color);v.setIncludeFontPadding(false);return v;}
 private TextView label(String s,int size){return text(s,size,0xff111111);}
 private void pad(View v,int n){v.setPadding(dp(n),dp(n),dp(n),dp(n));}
 private Icons icon(String name,String description,Runnable action){Icons i=new Icons(this,name);i.setContentDescription(description);i.setBackground(bg(Color.WHITE,0,24));i.setOnClickListener(v->action.run());i.setLayoutParams(new LinearLayout.LayoutParams(dp(48),dp(48)));return i;}
 private TextView pill(String s,boolean selected,Runnable action){TextView v=label(s,15);v.setGravity(Gravity.CENTER);v.setPadding(dp(15),dp(10),dp(15),dp(10));v.setBackground(bg(selected?0xfff0f0f0:Color.WHITE,selected?0xffbbbbbb:0xffe7e7e7,14));v.setOnClickListener(x->action.run());return v;}
 private String name(String s){return s.equals("kb")?"知识库":s.equals("llm")?"智能对话":"Octop";}
 private void ui(Runnable r){runOnUiThread(()->{if(!destroyed)r.run();});}
 private void error(Exception e){notice(e instanceof javax.net.ssl.SSLException?"HTTPS 证书验证失败，连接已终止。":e instanceof java.net.SocketTimeoutException?"连接超时，请检查网络或服务状态。":e.getMessage()==null?"操作失败，请重试。":e.getMessage());}
 private void notice(String s){if(!destroyed)new AlertDialog.Builder(this).setMessage(s).setPositiveButton("确定",null).show();}
 private void render(){thumbnailRequests=0;
  frame=new FrameLayout(this);frame.setBackgroundColor(Color.WHITE);root=col();frame.addView(root,new FrameLayout.LayoutParams(-1,-1));
  if(Build.VERSION.SDK_INT>=30)root.setOnApplyWindowInsetsListener((v,in)->{android.graphics.Insets e=in.getInsets(WindowInsets.Type.systemBars()|WindowInsets.Type.ime());v.setPadding(e.left,e.top,e.right,e.bottom);return in;});else root.setFitsSystemWindows(true);
  LinearLayout top=row();top.setPadding(dp(8),dp(6),dp(8),dp(4));top.addView(icon("menu","打开侧边栏",()->openDrawer()));
  TextView brand=label(page.equals("files")?"知识库文件":page.equals("work")?"工作台":page.equals("firewall")?"本地防火墙":"蔚蓝助手",17);brand.setGravity(Gravity.CENTER);top.addView(brand,new LinearLayout.LayoutParams(0,-2,1));
  top.addView(icon("plus","新建对话",()->newChat(service)));top.addView(icon("settings","账号与设置",()->settings()));root.addView(top);
  status=text("",12,0xff888888);status.setGravity(Gravity.CENTER);root.addView(status,new LinearLayout.LayoutParams(-1,dp(24)));
  body=col();root.addView(body,new LinearLayout.LayoutParams(-1,0,1));
  if(page.equals("files"))showFiles();else if(page.equals("work"))workBody();else if(page.equals("firewall"))firewallBody();else chatBody();
  setContentView(frame);drawer=null;
 }
 private void chatBody(){
  if(messages.length()==0){
   LinearLayout welcome=col();welcome.setGravity(Gravity.CENTER_HORIZONTAL);body.addView(welcome,new LinearLayout.LayoutParams(-1,0,1));
   View spacer=new View(this);welcome.addView(spacer,new LinearLayout.LayoutParams(1,0,1.5f));
   TextView hero=label("有什么我能帮你的吗？",26);hero.setTypeface(null,Typeface.BOLD);hero.setGravity(Gravity.CENTER);welcome.addView(hero);
   LinearLayout segment=row();segment.setPadding(dp(4),dp(4),dp(4),dp(4));segment.setBackground(bg(0xfff1f1f1,0,30));
   TextView talk=pill("对话",true,()->{}),task=pill("工作",false,()->{page="work";work=true;render();});talk.setBackground(bg(Color.WHITE,0,27));task.setBackground(bg(0xfff1f1f1,0,27));
   segment.addView(talk,new LinearLayout.LayoutParams(0,dp(48),1));segment.addView(task,new LinearLayout.LayoutParams(0,dp(48),1));LinearLayout.LayoutParams sp=new LinearLayout.LayoutParams(dp(250),dp(56));sp.topMargin=dp(24);welcome.addView(segment,sp);
   welcome.addView(new View(this),new LinearLayout.LayoutParams(1,0,1));
   LinearLayout suggestions=col();suggestions.setPadding(dp(18),0,dp(18),dp(14));TextView hint=text("为你推荐",14,0xff8a8a8a);suggestions.addView(hint);
   for(String q:new String[]{"查找公司的资质与项目资料","根据知识库整理投标材料清单","帮我梳理今天的工作安排"}){TextView chip=pill(q,false,()->{input.setText(q);input.setSelection(q.length());});LinearLayout.LayoutParams cp=new LinearLayout.LayoutParams(-2,-2);cp.topMargin=dp(10);suggestions.addView(chip,cp);}body.addView(suggestions);
  }else{
   conversation=new ScrollView(this);conversation.setFillViewport(true);chat=col();chat.setPadding(dp(18),dp(10),dp(18),dp(10));conversation.addView(chat);body.addView(conversation,new LinearLayout.LayoutParams(-1,0,1));
   for(int i=0;i<messages.length();i++){JSONObject m=messages.optJSONObject(i);if(m!=null)bubble(m.optString("role"),m.optString("content"));}
  }
  serviceRow();composer();status.setText(name(service)+" · "+(service.equals("octop")?(agent.isEmpty()?"请选择助手":"工作对话"):"对话"));
  scroll();
 }
 private TextView bubble(String role,String content){
  LinearLayout wrapper=col();boolean user=role.equals("user");wrapper.setGravity(user?Gravity.RIGHT:Gravity.LEFT);TextView v=label(user?content:FileReferences.display(content),17);v.setLineSpacing(dp(4),1);v.setTextIsSelectable(true);v.setPadding(dp(14),dp(12),dp(14),dp(12));v.setBackground(bg(user?0xfff2f2f2:Color.WHITE,0,20));
  if(!user){TextView who=text("蔚蓝 · "+name(service),12,0xff777777);who.setPadding(dp(12),dp(12),0,dp(4));wrapper.addView(who);}wrapper.addView(v,new LinearLayout.LayoutParams(user?-2:-1,-2));
  LinearLayout.LayoutParams lp=new LinearLayout.LayoutParams(-1,-2);lp.bottomMargin=dp(12);chat.addView(wrapper,lp);if(!user)addFileCards(wrapper,content);return v;
 }
 private void fileMenu(JSONObject ref){new AlertDialog.Builder(this).setTitle(ref.optString("name","文件")).setItems(new String[]{"打开原文件","保存到手机","分享到微信 / 其他应用"},(d,n)->openReference(ref,n)).setNegativeButton("取消",null).show();}
 private void addFileCards(LinearLayout wrapper,String content){try{JSONArray refs=FileReferences.parse(content);for(int i=0;i<refs.length();i++){JSONObject ref=refs.getJSONObject(i);String name=ref.optString("name","引用文件");boolean image=name.toLowerCase(Locale.ROOT).matches(".*\\.(jpg|jpeg|png|gif|webp|bmp)$");LinearLayout card=col();card.setBackground(bg(0xfff6f6f6,0xffe8e8e8,12));card.setClipToOutline(true);card.setOnClickListener(v->openReference(ref,0));card.setOnLongClickListener(v->{fileMenu(ref);return true;});card.setContentDescription(name+"，点击打开，长按保存或分享");
 if(image){ImageView thumb=new ImageView(this);thumb.setScaleType(ImageView.ScaleType.FIT_CENTER);thumb.setBackgroundColor(0xfff3f3f3);thumb.setContentDescription(name+"缩略图");card.addView(thumb,new LinearLayout.LayoutParams(dp(174),dp(218)));TextView caption=text("正在加载缩略图…",11,0xff888888);caption.setPadding(dp(10),dp(7),dp(10),dp(7));caption.setSingleLine(true);caption.setEllipsize(android.text.TextUtils.TruncateAt.END);card.addView(caption);loadThumbnail(ref,thumb,caption);}
 else{LinearLayout details=row();pad(details,12);String mime=ShareFiles.mime(name);TextView type=text(mime.equals("application/pdf")?"PDF":mime.contains("word")?"WORD":"FILE",12,Color.WHITE);type.setGravity(Gravity.CENTER);type.setTypeface(null,Typeface.BOLD);type.setBackground(bg(mime.equals("application/pdf")?0xffdf5454:0xff477bd5,0,8));details.addView(type,new LinearLayout.LayoutParams(dp(48),dp(56)));LinearLayout words=col();TextView filename=label(name,15);filename.setMaxLines(2);filename.setEllipsize(android.text.TextUtils.TruncateAt.END);words.addView(filename);TextView hint=text("点击打开 · 长按分享",11,0xff999999);hint.setPadding(0,dp(6),0,0);words.addView(hint);LinearLayout.LayoutParams wp=new LinearLayout.LayoutParams(0,-2,1);wp.leftMargin=dp(12);details.addView(words,wp);card.addView(details);}
 LinearLayout.LayoutParams lp=new LinearLayout.LayoutParams(image?dp(174):dp(278),-2);lp.topMargin=dp(10);wrapper.addView(card,lp);}}catch(Exception ignored){}}
 private JSONObject referenceFile(JSONObject ref)throws Exception{return referenceFile(api,ref);}
 private JSONObject referenceFile(ApiClient client,JSONObject ref)throws Exception{JSONObject chunk=ApiClient.object(client.request("kb","/api/v1/chunks/by-id/"+URLEncoder.encode(ref.getString("chunk_id"),"UTF-8"),"GET",null,true));String id=chunk.getString("knowledge_id");JSONObject knowledge=ApiClient.object(client.request("kb","/api/v1/knowledge/"+URLEncoder.encode(id,"UTF-8"),"GET",null,true));JSONObject metadata=knowledge.optJSONObject("custom_metadata");if(metadata==null)metadata=knowledge.optJSONObject("metadata");String path=metadata==null?"":metadata.optString("nas_path","");String base="/api/v1/knowledge/"+URLEncoder.encode(id,"UTF-8");JSONObject file=new JSONObject().put("name",knowledge.optString("file_name",ref.optString("name"))).put("path",path);if(!path.isEmpty())file.put("name",path.replace("\\","/").substring(path.replace("\\","/").lastIndexOf("/")+1));if(path.isEmpty())file.put("_raw",base+"/preview").put("_download",base+"/download");return file;}
 private void loadThumbnail(JSONObject ref,ImageView view,TextView caption){final FrameLayout screen=frame;final String expected;try{expected=profile("kb");}catch(Exception e){caption.setText("点击查看 · 长按分享");return;}String key=expected+"|"+ref.optString("chunk_id");android.graphics.Bitmap cached=thumbnailCache.get(key);if(cached!=null){view.setImageBitmap(cached);caption.setText("点击放大 · 长按分享");return;}if(thumbnailRequests++>=20){caption.setText("点击查看 · 长按分享");return;}thumbnails.execute(()->{javax.net.ssl.HttpsURLConnection c=null;try{ApiClient client=new ApiClient(store);JSONObject file=referenceFile(client,ref);c=client.open("kb",rawPath(file),"GET",null,true);ApiClient.check(c);String type=c.getContentType();if(type==null||!type.toLowerCase(Locale.ROOT).startsWith("image/"))throw new IOException("非图片");byte[] data=ApiClient.bytes(c.getInputStream(),12*1024*1024);android.graphics.BitmapFactory.Options options=new android.graphics.BitmapFactory.Options();options.inJustDecodeBounds=true;android.graphics.BitmapFactory.decodeByteArray(data,0,data.length,options);if(options.outWidth<=0||options.outHeight<=0)throw new IOException("无效图片");options.inSampleSize=1;while(Math.max(options.outWidth,options.outHeight)/options.inSampleSize>512)options.inSampleSize*=2;options.inJustDecodeBounds=false;android.graphics.Bitmap bitmap=android.graphics.BitmapFactory.decodeByteArray(data,0,data.length,options);if(bitmap==null)throw new IOException("解码失败");if(!expected.equals(profile("kb")))return;thumbnailCache.put(key,bitmap);ui(()->{try{if(frame!=screen||!expected.equals(profile("kb")))return;view.setImageBitmap(bitmap);int height=Math.max(96,Math.min(240,Math.round(174f*bitmap.getHeight()/bitmap.getWidth())));view.setLayoutParams(new LinearLayout.LayoutParams(dp(174),dp(height)));caption.setText("点击放大 · 长按分享");}catch(Exception ignored){}});}catch(Exception e){ui(()->{if(frame==screen)caption.setText("点击查看原图 · 长按分享");});}finally{if(c!=null)c.disconnect();}});}
 private void openReference(JSONObject ref,int action){status.setText("正在读取原文件…");jobs.execute(()->{try{String expected=profile("kb");JSONObject file=referenceFile(ref);ui(()->{try{if(!expected.equals(profile("kb")))throw new Exception("账号已改变，请重新打开文件。");String name=file.optString("name").toLowerCase(Locale.ROOT);if(action==1)download(file);else if(action==2)externalFile(file,true);else if(name.matches(".*\\.(jpg|jpeg|png|gif|webp|bmp)$"))previewImage(file);else externalFile(file,false);}catch(Exception e){error(e);}});}catch(Exception e){ui(()->{status.setText("原文件读取失败");error(e);});}});}
 private void externalFile(JSONObject file,boolean share){status.setText("正在下载原文件…");jobs.execute(()->{javax.net.ssl.HttpsURLConnection c=null;File target=null;boolean complete=false;try{String expected=profile("kb"),name=ShareFiles.safeName(file.optString("name","文件"));String key=UUID.randomUUID().toString();target=ShareFiles.resolve(new File(getCacheDir(),"shared"),key,name);target.getParentFile().mkdirs();c=api.open("kb",file.optString("_download",rawPath(file)),"GET",null,true);ApiClient.check(c);String type=c.getContentType();if(type==null||type.toLowerCase(Locale.ROOT).contains("text/html")||type.toLowerCase(Locale.ROOT).contains("application/json"))throw new IOException("服务器没有返回原文件");long length=c.getContentLengthLong(),count=0;if(length>100L*1024*1024)throw new IOException("文件超过100MB，请在浏览器下载");try(InputStream in=c.getInputStream();OutputStream out=new FileOutputStream(target)){byte[] buffer=new byte[65536];int n;while((n=in.read(buffer))!=-1){count+=n;if(count>100L*1024*1024)throw new IOException("文件超过100MB");out.write(buffer,0,n);}}if(count==0||(length>=0&&count!=length))throw new IOException("文件传输不完整");if(!expected.equals(profile("kb")))throw new IOException("登录状态已改变");complete=true;Uri uri=new Uri.Builder().scheme("content").authority(getPackageName()+".sharedfiles").appendPath(key).appendPath(name).build();ui(()->{try{if(!expected.equals(profile("kb")))throw new IOException("登录状态已改变");Intent intent=new Intent(share?Intent.ACTION_SEND:Intent.ACTION_VIEW);if(share){intent.setType(ShareFiles.mime(name));intent.putExtra(Intent.EXTRA_STREAM,uri);}else intent.setDataAndType(uri,ShareFiles.mime(name));intent.setClipData(ClipData.newRawUri(name,uri));intent.addFlags(Intent.FLAG_GRANT_READ_URI_PERMISSION);startActivity(Intent.createChooser(intent,share?"选择微信或其他应用":"选择打开文件的应用"));status.setText("原文件已准备好");}catch(ActivityNotFoundException e){notice("手机没有可打开此文件的应用，请安装WPS或PDF阅读器，也可以先保存文件。");}catch(Exception e){error(e);}});}catch(Exception e){ui(()->error(e));}finally{if(c!=null)c.disconnect();if(!complete&&target!=null)target.delete();}});}
 private void scroll(){if(conversation!=null)conversation.post(()->conversation.fullScroll(View.FOCUS_DOWN));}
 private void serviceRow(){LinearLayout r=row();r.setPadding(dp(18),dp(6),dp(18),dp(12));
  for(String svc:new String[]{"kb","llm","octop"}){TextView v=pill(name(svc),service.equals(svc),()->switchService(svc));LinearLayout.LayoutParams lp=new LinearLayout.LayoutParams(0,dp(44),1);lp.rightMargin=dp(8);r.addView(v,lp);}root.addView(r);
 }
 private void composer(){composer=row();composer.setPadding(dp(4),dp(4),dp(6),dp(4));composer.setBackground(bg(Color.WHITE,0xffe6e6e6,28));composer.setElevation(dp(3));
  composer.addView(icon("attach","添加文本附件",()->pickText()));input=new EditText(this);input.setTextSize(16);input.setTextColor(0xff111111);input.setHint("发消息或说话…");input.setHintTextColor(0xff999999);input.setBackgroundColor(Color.TRANSPARENT);input.setMaxLines(4);input.setInputType(android.text.InputType.TYPE_CLASS_TEXT|android.text.InputType.TYPE_TEXT_FLAG_MULTI_LINE|android.text.InputType.TYPE_TEXT_FLAG_CAP_SENTENCES);composer.addView(input,new LinearLayout.LayoutParams(0,-2,1));
  composer.addView(icon("mic","语音输入",()->voice()));send=icon(busy?"stop":"send",busy?"停止接收回答":"发送消息",()->{if(busy)stopChat();else sendChat();});composer.addView(send);
  LinearLayout.LayoutParams cp=new LinearLayout.LayoutParams(-1,-2);cp.leftMargin=dp(14);cp.rightMargin=dp(14);cp.bottomMargin=dp(16);root.addView(composer,cp);
 }
 private void switchService(String svc){if(busy){notice("请先停止当前回答。");return;}service=svc;try{store.put("last_service",svc);}catch(Exception e){error(e);}newChat(svc);}
 private void newChat(String svc){if(busy){notice("请先停止当前回答。");return;}generation++;service=svc;session="";title="新对话";recordId="";messages=new JSONArray();attachments=new JSONArray();page="chat";profile="";render();}
 private String profile(String svc) throws Exception {if(svc.equals("llm"))svc="kb";String token=api.token(svc);String identity=api.get(svc+"_identity","");if(!identity.isEmpty())return api.endpoint(svc)+"|"+api.get(svc+"_tenant","")+"|"+identity;java.security.MessageDigest h=java.security.MessageDigest.getInstance("SHA-256");return api.endpoint(svc)+"|"+api.get(svc+"_tenant","")+"|"+android.util.Base64.encodeToString(h.digest(token.getBytes("UTF-8")),android.util.Base64.NO_WRAP);}
 private void sendChat(){
  String query=input.getText().toString().trim();if(query.isEmpty())return;
  try{api.token(service.equals("llm")?"kb":service);String now=profile(service);if(!profile.isEmpty()&&!profile.equals(now))throw new Exception("连接或账号已改变，请新建对话。");profile=now;if(service.equals("octop")&&agent.isEmpty())throw new Exception("请先在工作台选择 Octop 助手。");}
  catch(Exception e){error(e);return;}
  input.setText("");((InputMethodManager)getSystemService(INPUT_METHOD_SERVICE)).hideSoftInputFromWindow(input.getWindowToken(),0);
  busy=true;api.start();final String svc=service;final int turn=++generation;
  try{messages.put(new JSONObject().put("role","user").put("content",query));messages.put(new JSONObject().put("role","assistant").put("content",""));if(title.equals("新对话"))title=query.substring(0,Math.min(24,query.length()));}
  catch(Exception e){busy=false;error(e);return;}
  final JSONObject answer=messages.optJSONObject(messages.length()-1);final JSONArray requestMessages=new JSONArray();
  for(int i=0;i<messages.length()-1;i++)requestMessages.put(messages.opt(i));
  render();final TextView answerView=chat==null?null:(TextView)((LinearLayout)chat.getChildAt(chat.getChildCount()-1)).getChildAt(1);status.setText("正在连接 "+name(svc)+"…");
  final StringBuilder output=new StringBuilder();final LinkedHashSet<String> references=new LinkedHashSet<>();
  jobs.execute(()->{
   try{
    ApiClient.Listener listener=new ApiClient.Listener(){public void text(String chunk){if(chunk.isEmpty())return;output.append(chunk);if(output.length()>1024*1024){api.cancel();return;}ui(()->{if(turn!=generation)return;try{answer.put("content",output.toString());}catch(Exception ignored){}if(answerView!=null)answerView.setText(FileReferences.display(output.toString()));status.setText(name(svc)+" · 正在回答");scroll();});}
     public void meta(JSONObject data){
      String kind=data.optString("response_type",data.optString("type"));
      if(svc.equals("kb")){
       if(kind.equals("tool_call")){output.setLength(0);ui(()->{if(turn==generation&&answerView!=null)answerView.setText("正在检索资料…");});}
       JSONArray refs=data.optJSONArray("knowledge_references");JSONObject extra=data.optJSONObject("data");if(refs==null&&extra!=null)refs=extra.optJSONArray("references");
       if(refs!=null)for(int i=0;i<refs.length()&&references.size()<20;i++){JSONObject ref=refs.optJSONObject(i);if(ref!=null){String title=ref.optString("knowledge_title",ref.optString("knowledge_filename",""));if(!title.isEmpty())references.add(title);}}
      }
      if(svc.equals("octop")){String id=data.optString("thread_id","");if(!id.isEmpty())session=id;}if(data.optString("type").equals("interrupt"))ui(()->{if(turn==generation)status.setText("任务等待审批，请在 Octop 管理端处理");});}};
    if(svc.equals("kb")||svc.equals("llm")){
     JSONObject options=AccountChat.prepare(api);
     if(session.isEmpty()){JSONObject created=ApiClient.object(api.request("kb","/api/v1/sessions","POST",new JSONObject().put("title",title).put("description",svc.equals("llm")?"蔚蓝助手 · 智能对话":"蔚蓝助手 · 知识库"),true));session=created.getString("id");}
     JSONObject body=AccountChat.request(query,svc.equals("kb"),options.getString("model_id"),options.getJSONArray("knowledge_base_ids"));
     api.stream("kb","/api/v1/knowledge-chat/"+URLEncoder.encode(session,"UTF-8"),body,listener);
    }
    else {if(session.isEmpty())session="mobile:"+UUID.randomUUID();api.octop(agent,session,query,listener);}
    ui(()->{if(turn!=generation)return;String reply=output.toString();if(!references.isEmpty()){StringBuilder sources=new StringBuilder("\n\n资料来源：");for(String source:references)sources.append("\n• ").append(source);reply+=sources.toString();}finishChat(reply,false);});
   }catch(Exception e){ui(()->{if(turn!=generation)return;String suffix=api.cancelled?"\n\n[已停止接收]":"\n\n[未完成："+safeError(e)+"]";finishChat(output.toString()+suffix,true);});}
  });
 }
 private String safeError(Exception e){if(e instanceof javax.net.ssl.SSLException)return "HTTPS 证书验证失败";if(e instanceof java.net.SocketTimeoutException)return "连接超时";if(e instanceof java.net.UnknownHostException)return "无法解析服务器地址";return e.getMessage()==null?"连接失败":e.getMessage();}
 private void finishChat(String content,boolean failed){busy=false;try{messages.getJSONObject(messages.length()-1).put("content",content.isEmpty()?"服务未返回文字，请检查模型配置。":content);saveHistory();}catch(Exception e){error(e);}render();status.setText(failed?"回答未完成，可检查配置后重试":name(service)+" · 回答完成");if(speak&&!failed&&tts!=null)tts.speak(content,TextToSpeech.QUEUE_FLUSH,null,"reply");}
 private void stopChat(){api.cancel();status.setText("正在停止接收…");}
 private void saveHistory() throws Exception {
  if(recordId.isEmpty())recordId=UUID.randomUUID().toString();JSONObject record=new JSONObject().put("id",recordId).put("title",title).put("service",service).put("session",session).put("agent",agent).put("profile",profile).put("messages",messages).put("time",System.currentTimeMillis());
  JSONArray next=new JSONArray();next.put(record);for(int i=0;i<history.length()&&next.length()<20&&next.toString().length()<2*1024*1024;i++){JSONObject item=history.optJSONObject(i);if(item!=null&&!recordId.equals(item.optString("id")))next.put(item);}history=next;store.put("history",history.toString());
 }
 private void openDrawer(){if(drawer!=null)return;FrameLayout overlay=new FrameLayout(this);View scrim=new View(this);scrim.setBackgroundColor(0x33000000);scrim.setOnClickListener(v->closeDrawer());overlay.addView(scrim,new FrameLayout.LayoutParams(-1,-1));
  LinearLayout panel=col();panel.setBackgroundColor(Color.WHITE);panel.setPadding(dp(20),dp(30),dp(20),dp(18));FrameLayout.LayoutParams pp=new FrameLayout.LayoutParams((int)(getResources().getDisplayMetrics().widthPixels*.84),-1,Gravity.LEFT);overlay.addView(panel,pp);
  LinearLayout header=row();TextView heading=label("蔚蓝助手",25);heading.setTypeface(null,Typeface.BOLD);header.addView(heading,new LinearLayout.LayoutParams(0,-2,1));header.addView(icon("search","查找历史对话",()->searchHistory()));panel.addView(header);
  nav(panel,"plus","新对话",()->newChat(service));nav(panel,"clock","Octop 工作台",()->{if(busy){notice("请先停止当前回答。");return;}page="work";render();});nav(panel,"link","账号与设置",()->settings());nav(panel,"shield","本地防火墙",()->openFirewall());nav(panel,"folder","知识库文件",()->{if(busy){notice("请先停止当前回答。");return;}page="files";render();});
  nav(panel,"chat","浏览器同步会话",()->serverHistory("",1));nav(panel,"clock","刷新当前对话",()->refreshConversation());TextView recent=text("最近 · 本机缓存",13,0xff999999);recent.setPadding(0,dp(20),0,dp(10));panel.addView(recent);
  ScrollView list=new ScrollView(this);LinearLayout entries=col();list.addView(entries);panel.addView(list,new LinearLayout.LayoutParams(-1,0,1));for(int i=0;i<history.length();i++){JSONObject item=history.optJSONObject(i);if(item==null||!visibleHistory(item))continue;nav(entries,"chat",item.optString("title"),()->loadHistory(item));}
  if(history.length()==0){TextView empty=text("开始对话后，记录会出现在这里",14,0xff999999);entries.addView(empty);}
  View divider=new View(this);divider.setBackgroundColor(0xffeeeeee);panel.addView(divider,new LinearLayout.LayoutParams(-1,dp(1)));nav(panel,"settings","账号与设置",()->settings());panel.addView(text("知识库 · 智能对话 · Octop",12,0xff888888));
  drawer=overlay;frame.addView(overlay,new FrameLayout.LayoutParams(-1,-1));panel.setTranslationX(-pp.width);panel.animate().translationX(0).setDuration(180).start();
 }
 private void closeDrawer(){if(drawer!=null){frame.removeView(drawer);drawer=null;}}
 private void nav(LinearLayout panel,String ic,String title,Runnable action){LinearLayout r=row();Icons image=new Icons(this,ic);r.addView(image,new LinearLayout.LayoutParams(dp(40),dp(52)));TextView t=label(title,17);t.setSingleLine(true);t.setEllipsize(android.text.TextUtils.TruncateAt.END);r.addView(t,new LinearLayout.LayoutParams(0,dp(52),1));t.setGravity(Gravity.CENTER_VERTICAL);r.setContentDescription(title);r.setOnClickListener(v->{closeDrawer();action.run();});panel.addView(r);}
 private boolean visibleHistory(JSONObject item){try{return item.optString("profile").equals(profile(item.getString("service")));}catch(Exception e){return false;}}
 private void loadHistory(JSONObject item){if(!item.optString("service").equals("octop")&&!item.optString("session").isEmpty()){loadServerConversation(item.optString("session"),item.optString("title"),item.optString("service"));return;}if(busy){notice("请先停止当前回答。");return;}try{String svc=item.getString("service");if(!item.optString("profile").equals(profile(svc)))throw new Exception("此会话属于另一连接或登录状态，请恢复对应账号后查看。");generation++;service=svc;title=item.getString("title");recordId=item.getString("id");session=item.optString("session");agent=item.optString("agent");profile=item.getString("profile");messages=new JSONArray(item.getJSONArray("messages").toString());page="chat";render();}catch(Exception e){error(e);}}
 private void searchHistory(){EditText q=new EditText(this);q.setHint("输入服务端对话标题");new AlertDialog.Builder(this).setTitle("查找同步对话").setView(q).setPositiveButton("搜索",(d,w)->serverHistory(q.getText().toString(),1)).setNegativeButton("取消",null).show();}
 private void serverHistory(String keyword,int pageNumber){if(busy){notice("请先停止当前回答。");return;}status.setText("正在读取浏览器同步会话…");jobs.execute(()->{try{String expected=profile("kb");JSONObject result=(JSONObject)api.request("kb","/api/v1/sessions?page="+pageNumber+"&page_size=50&keyword="+URLEncoder.encode(keyword,"UTF-8"),"GET",null,true);JSONArray records=ApiClient.array(result,"data");ArrayList<String> labels=new ArrayList<>();for(int i=0;i<records.length();i++)labels.add(records.getJSONObject(i).optString("title","新对话"));boolean more=pageNumber*50<result.optInt("total",records.length());if(more)labels.add("下一页 →");ui(()->{try{if(!expected.equals(profile("kb")))return;}catch(Exception e){return;}status.setText("已读取服务端会话");new AlertDialog.Builder(this).setTitle("浏览器同步会话 · 第 "+pageNumber+" 页").setItems(labels.toArray(new String[0]),(d,n)->{if(n==records.length()){serverHistory(keyword,pageNumber+1);return;}JSONObject r=records.optJSONObject(n);loadServerConversation(r.optString("id"),r.optString("title","新对话"),(r.optString("description").contains("智能对话")||r.optString("description").contains("HY4 Preview")||r.optString("description").contains("GLM Flash"))?"llm":"kb");}).setNegativeButton("关闭",null).show();});}catch(Exception e){ui(()->error(e));}});}
 private void refreshConversation(){if(session.isEmpty()||service.equals("octop")){serverHistory("",1);return;}loadServerConversation(session,title,service);}
 private void loadServerConversation(String id,String heading,String svc){if(busy){notice("请先停止当前回答。");return;}final int turn=++generation;status.setText("正在同步对话…");jobs.execute(()->{try{String expected=profile("kb");JSONArray raw=ApiClient.array(api.request("kb","/api/v1/messages/"+URLEncoder.encode(id,"UTF-8")+"/load?limit=100","GET",null,true),"data");ArrayList<JSONObject> ordered=new ArrayList<>();for(int i=0;i<raw.length();i++){JSONObject m=raw.optJSONObject(i);if(m!=null&&(m.optString("role").equals("user")||m.optString("role").equals("assistant")))ordered.add(m);}Collections.sort(ordered,(a,b)->a.optString("created_at").compareTo(b.optString("created_at")));JSONArray loaded=new JSONArray();for(JSONObject m:ordered)loaded.put(new JSONObject().put("role",m.optString("role")).put("content",m.optString("content")));ui(()->{if(turn!=generation||busy)return;try{if(!expected.equals(profile("kb")))return;service=svc;session=id;title=heading;profile=expected;recordId=id;messages=loaded;page="chat";saveHistory();render();status.setText("已与浏览器同步"+(raw.length()>=100?" · 显示最近 100 条":""));}catch(Exception e){error(e);}});}catch(Exception e){ui(()->{if(turn==generation){status.setText("同步失败，未覆盖当前对话");error(e);}});}});}
 @Override protected void onResume(){super.onResume();if(api!=null&&status!=null&&!busy&&page.equals("chat")&&!session.isEmpty()&&!service.equals("octop"))refreshConversation();}


 private void settings(){if(busy){notice("请先停止当前回答再修改账号。");return;}
  new AlertDialog.Builder(this).setTitle("账号与设置").setItems(new String[]{"账号密码登录","检查账号与 APP 模型","本地防火墙","语音播报："+(speak?"开启":"关闭"),"退出登录","清除本机对话记录"},(d,n)->{
   if(n==0)login("kb");else if(n==1)checkAccount();else if(n==2)openFirewall();else if(n==3){if(!ttsReady){notice("手机上的语音播报服务尚不可用。");return;}speak=!speak;notice(speak?"已开启回答播报":"已关闭回答播报");}else if(n==4)clearCredentials();else clearHistory();
  }).setNegativeButton("关闭",null).show();
 }
 private void checkAccount(){status.setText("正在检查账号和模型…");jobs.execute(()->{try{api.request("kb","/api/v1/auth/me","GET",null,true);JSONObject options=AccountChat.prepare(api);ui(()->{status.setText("账号与 APP 模型已就绪");notice("账号验证通过，网页配置的 APP 模型已就绪；当前可访问 "+options.optJSONArray("knowledge_base_ids").length()+" 个知识库。");});}catch(Exception e){ui(()->error(e));}});}
 private EditText field(LinearLayout form,String caption,String value,boolean secret){TextView t=text(caption,13,0xff777777);LinearLayout.LayoutParams lp=new LinearLayout.LayoutParams(-1,-2);lp.topMargin=dp(14);form.addView(t,lp);EditText e=new EditText(this);e.setTextSize(15);e.setSingleLine(true);e.setText(value);e.setPadding(dp(10),dp(10),dp(10),dp(10));e.setBackground(bg(0xfff7f7f7,0xffe5e5e5,10));e.setInputType(android.text.InputType.TYPE_CLASS_TEXT|(secret?android.text.InputType.TYPE_TEXT_VARIATION_PASSWORD:android.text.InputType.TYPE_TEXT_VARIATION_VISIBLE_PASSWORD));form.addView(e,new LinearLayout.LayoutParams(-1,-2));return e;}
 private void login(String svc){
  LinearLayout form=col();pad(form,20);EditText account=field(form,svc.equals("kb")?"账号（知识库登录邮箱）":"用户名或邮箱","",false),password=field(form,"密码","",true);
  AlertDialog dialog=new AlertDialog.Builder(this).setTitle("登录 "+name(svc)).setView(form).setNegativeButton("取消",null).setPositiveButton("登录",null).create();
  dialog.setOnShowListener(d->{dialog.getWindow().addFlags(WindowManager.LayoutParams.FLAG_SECURE);dialog.getButton(-1).setOnClickListener(v->{String user=account.getText().toString().trim(),pass=password.getText().toString();if(user.isEmpty()||pass.isEmpty()){notice("请填写账号和密码。");return;}dialog.getButton(-1).setEnabled(false);
   jobs.execute(()->{try{JSONObject body=new JSONObject().put(svc.equals("kb")?"email":"username",user).put("password",pass);JSONObject result=ApiClient.object(api.request(svc,svc.equals("kb")?"/api/v1/auth/login":"/api/auth/login","POST",body,false));
    String jwt=result.optString(svc.equals("kb")?"token":"access_token","");if(jwt.isEmpty())throw new Exception("登录未成功，请检查账号和密码；若系统启用验证码，请联系管理员开通手机登录。");
    store.put(svc+"_token",jwt);JSONObject accountInfo=result.optJSONObject("user");if(accountInfo!=null&&!accountInfo.optString("id","").isEmpty())store.put(svc+"_identity","user:"+accountInfo.optString("id"));JSONObject tenant=result.optJSONObject("active_tenant");if(tenant==null)tenant=result.optJSONObject("tenant");if(svc.equals("kb")&&tenant!=null)store.put("kb_tenant",String.valueOf(tenant.getLong("id")));
    ui(()->{password.setText("");dialog.dismiss();newChat("kb");notice("登录成功。模型和可用知识库会自动读取，不需要填写密钥。");});
   }catch(Exception e){ui(()->{dialog.getButton(-1).setEnabled(true);error(e);});}});
  });});dialog.show();
 }
 private void clearCredentials(){new AlertDialog.Builder(this).setTitle("清除登录与密钥").setMessage("清除本机保存的三个服务凭据，之后需要重新登录或绑定。").setPositiveButton("清除",(d,w)->{for(String s:new String[]{"kb","llm","octop"}){store.remove(s+"_token");store.remove(s+"_identity");}store.remove("kb_tenant");newChat(service);}).setNegativeButton("取消",null).show();}
 private void clearHistory(){new AlertDialog.Builder(this).setTitle("清除本机对话记录").setMessage("只删除本机记录；服务端会话仍保留。").setPositiveButton("清除",(d,w)->{store.remove("history");history=new JSONArray();newChat(service);}).setNegativeButton("取消",null).show();}
 private void workBody(){ScrollView scroll=new ScrollView(this);LinearLayout content=col();content.setPadding(dp(20),dp(24),dp(20),dp(24));scroll.addView(content);body.addView(scroll,new LinearLayout.LayoutParams(-1,0,1));TextView title=label("让助手帮你完成工作",25);title.setTypeface(null,Typeface.BOLD);content.addView(title);TextView intro=text("选择 Octop 助手，查看定时任务，或连接你自己的模型。",15,0xff888888);intro.setPadding(0,dp(14),0,dp(24));content.addView(intro);
  nav(content,"chat","选择 Octop 助手",()->listAgents());nav(content,"clock","查看定时任务",()->listCron());nav(content,"link","任务权限模式",()->chooseMode());nav(content,"folder","查阅知识库文件",()->{page="files";render();});nav(content,"shield","本地防火墙",()->openFirewall());nav(content,"settings","账号与设置",()->settings());nav(content,"back","返回对话",()->{page="chat";render();});
  try{String id=agent.isEmpty()?api.get("octop_agent",""):agent;content.addView(text(id.isEmpty()?"尚未选择助手":"当前助手："+id,13,0xff888888));content.addView(text("任务权限："+api.get("octop_mode","ask"),13,0xff888888));}catch(Exception e){error(e);}
 }
 private void listAgents(){status.setText("正在获取 Octop 助手…");jobs.execute(()->{try{JSONArray items=ApiClient.array(api.request("octop","/api/agents?scope=mine","GET",null,true),"agents","items");String[] names=new String[items.length()];for(int i=0;i<names.length;i++){JSONObject a=items.getJSONObject(i);names[i]=a.optString("name",a.optString("display_name",a.optString("agent_id",a.optString("id"))));}
  ui(()->{status.setText("已读取 "+names.length+" 个助手");new AlertDialog.Builder(this).setTitle("选择你的助手").setItems(names,(d,n)->{try{JSONObject a=items.getJSONObject(n);agent=a.optString("agent_id",a.optString("id",""));if(agent.isEmpty())throw new Exception("助手未返回 ID");store.put("octop_agent",agent);newChat("octop");}catch(Exception e){error(e);}}).setNegativeButton("关闭",null).show();});
 }catch(Exception e){ui(()->error(e));}});}
 private void chooseMode(){new AlertDialog.Builder(this).setTitle("Octop 任务权限").setItems(new String[]{"只读问答（ask）","生成计划（plan）","执行工作（craft）"},(d,n)->{try{store.put("octop_mode",new String[]{"ask","plan","craft"}[n]);render();}catch(Exception e){error(e);}}).setNegativeButton("取消",null).show();}
 private void listCron(){try{if(agent.isEmpty())agent=api.get("octop_agent","");if(agent.isEmpty()){listAgents();return;}}catch(Exception e){error(e);return;}jobs.execute(()->{try{JSONArray tasks=ApiClient.array(api.request("octop","/api/agents/"+URLEncoder.encode(agent,"UTF-8")+"/cron","GET",null,true),"jobs","items");ArrayList<String> labels=new ArrayList<>();for(int i=0;i<tasks.length();i++){JSONObject t=tasks.getJSONObject(i);labels.add(t.optString("name",t.optString("cron_id",t.optString("id")))+" · "+(t.optBoolean("enabled")?"启用":"停用"));}
  ui(()->new AlertDialog.Builder(this).setTitle("定时任务（"+tasks.length()+"）").setItems(labels.toArray(new String[0]),(d,n)->{JSONObject t=tasks.optJSONObject(n);notice(t.optString("name")+"\n\n"+t.optString("prompt")+"\n\n"+t.optString("trigger"));}).setNegativeButton("关闭",null).show());
 }catch(Exception e){ui(()->error(e));}});}

 private int filePage=1;private EditText fileSearch;private LinearLayout fileList;private TextView fileCount;
 private void showFiles(){
  LinearLayout search=row();search.setPadding(dp(18),dp(14),dp(18),dp(14));fileSearch=new EditText(this);fileSearch.setTextSize(15);fileSearch.setSingleLine(true);fileSearch.setHint("搜索文件名、公司或 NAS 路径");fileSearch.setBackground(bg(0xfff5f5f5,0,12));pad(fileSearch,12);search.addView(fileSearch,new LinearLayout.LayoutParams(0,dp(48),1));search.addView(icon("search","搜索知识库文件",()->{filePage=1;loadFiles();}));body.addView(search);
  fileCount=text("当前账号可见的文件",13,0xff888888);fileCount.setPadding(dp(20),0,dp(20),dp(10));body.addView(fileCount);ScrollView list=new ScrollView(this);fileList=col();fileList.setPadding(dp(18),0,dp(18),dp(18));list.addView(fileList);body.addView(list,new LinearLayout.LayoutParams(-1,0,1));
  LinearLayout nav=row();pad(nav,12);TextView previous=pill("上一页",false,()->{if(filePage>1){filePage--;loadFiles();}}),next=pill("下一页",false,()->{filePage++;loadFiles();}),back=pill("返回对话",false,()->{page="chat";render();});nav.addView(previous,new LinearLayout.LayoutParams(0,-2,1));nav.addView(next,new LinearLayout.LayoutParams(0,-2,1));nav.addView(back,new LinearLayout.LayoutParams(0,-2,1));body.addView(nav);loadFiles();
 }
 private void loadFiles(){final int turn=++generation,requested=filePage;final String query=fileSearch.getText().toString();status.setText("正在读取文件目录…");jobs.execute(()->{try{JSONObject result=ApiClient.object(api.request("kb","/api/v1/nas/files?q="+URLEncoder.encode(query,"UTF-8")+"&page="+requested,"GET",null,true));JSONArray files=result.getJSONArray("files");int total=result.optInt("total",files.length());
  ui(()->{if(turn!=generation||!page.equals("files"))return;fileList.removeAllViews();fileCount.setText("找到 "+total+" 个文件 · 第 "+requested+" 页");status.setText("知识库 · 当前账号权限范围");
   for(int i=0;i<files.length();i++){JSONObject file=files.optJSONObject(i);if(file==null)continue;LinearLayout card=col();pad(card,16);card.setBackground(bg(Color.WHITE,0xffe5e5e5,14));TextView heading=label(file.optString("name"),17);heading.setTypeface(null,Typeface.BOLD);card.addView(heading);TextView path=text(file.optString("path"),12,0xff777777);path.setTextIsSelectable(true);path.setPadding(0,dp(10),0,dp(10));card.addView(path);card.addView(text(String.format(Locale.CHINA,"%.2f MB · %s",file.optDouble("size")/1048576,file.optString("state")),12,0xff888888));LinearLayout actions=row();
    if(file.optBoolean("preview_available")){TextView preview=pill("查看原图",false,()->previewImage(file));actions.addView(preview);}
    TextView download=file.optBoolean("preview_available")?pill("保存原图",false,()->download(file)):pill("复制 NAS 路径",false,()->{((android.content.ClipboardManager)getSystemService(CLIPBOARD_SERVICE)).setPrimaryClip(ClipData.newPlainText("NAS 路径",file.optString("path")));Toast.makeText(this,"NAS 路径已复制",Toast.LENGTH_SHORT).show();});LinearLayout.LayoutParams button=new LinearLayout.LayoutParams(-2,-2);button.leftMargin=dp(8);actions.addView(download,button);card.addView(actions);LinearLayout.LayoutParams lp=new LinearLayout.LayoutParams(-1,-2);lp.bottomMargin=dp(12);fileList.addView(card,lp);
   }if(files.length()==0)fileList.addView(text("本页没有文件。可以更换搜索条件或返回上一页。",15,0xff777777));
  });
 }catch(Exception e){ui(()->{if(turn!=generation)return;status.setText("目录读取失败");error(e);});}});}
 private String rawPath(JSONObject file) throws Exception {if(file.has("_raw"))return file.getString("_raw");return "/api/v1/nas/files/raw?path="+URLEncoder.encode(file.getString("path"),"UTF-8");}
 private void previewImage(JSONObject file){status.setText("正在加载原图…");jobs.execute(()->{javax.net.ssl.HttpsURLConnection c=null;try{c=api.open("kb",rawPath(file),"GET",null,true);ApiClient.check(c);String type=c.getContentType();if(type==null||!type.toLowerCase(Locale.ROOT).startsWith("image/"))throw new Exception("此文件未返回可预览图片。");byte[] data=ApiClient.bytes(c.getInputStream(),32*1024*1024);
  android.graphics.BitmapFactory.Options options=new android.graphics.BitmapFactory.Options();options.inJustDecodeBounds=true;android.graphics.BitmapFactory.decodeByteArray(data,0,data.length,options);if(options.outWidth<=0||options.outHeight<=0)throw new Exception("图片格式不支持。");options.inJustDecodeBounds=false;options.inSampleSize=1;while((long)options.outWidth*options.outHeight/(options.inSampleSize*options.inSampleSize)>12000000L)options.inSampleSize*=2;
  android.graphics.Bitmap bitmap=android.graphics.BitmapFactory.decodeByteArray(data,0,data.length,options);if(bitmap==null)throw new Exception("图片解码失败。");ui(()->{status.setText("原图加载完成");Dialog dialog=new Dialog(this,android.R.style.Theme_Material_Light_NoActionBar);LinearLayout layout=col();layout.setBackgroundColor(Color.WHITE);LinearLayout toolbar=row();toolbar.addView(icon("back","关闭原图",()->dialog.dismiss()));TextView title=label(file.optString("name"),16);title.setSingleLine(true);title.setEllipsize(android.text.TextUtils.TruncateAt.END);toolbar.addView(title,new LinearLayout.LayoutParams(0,-2,1));toolbar.addView(icon("folder","保存原文件",()->download(file)));layout.addView(toolbar);ZoomImage image=new ZoomImage(this,bitmap);layout.addView(image,new LinearLayout.LayoutParams(-1,0,1));TextView tip=text("双指缩放 · 拖动查看 · 双击适应屏幕",13,0xff777777);tip.setGravity(Gravity.CENTER);pad(tip,14);layout.addView(tip);dialog.setContentView(layout);dialog.setOnDismissListener(d->bitmap.recycle());dialog.show();dialog.getWindow().setLayout(-1,-1);});
 }catch(Exception e){ui(()->error(e));}finally{if(c!=null)c.disconnect();}});}
 private void download(JSONObject file){try{if(!downloadPath.isEmpty()){notice("请先完成当前保存操作。");return;}api.token("kb");downloadPath=file.optString("_download",rawPath(file));downloadProfile=profile("kb");Intent intent=new Intent(Intent.ACTION_CREATE_DOCUMENT);intent.addCategory(Intent.CATEGORY_OPENABLE);intent.setType("application/octet-stream");String filename=file.optString("name","知识库文件").replaceAll("[\\\\/:*?\"<>|\\p{Cntrl}]","_");intent.putExtra(Intent.EXTRA_TITLE,filename);startActivityForResult(intent,SAVE_FILE);}catch(Exception e){downloadPath="";error(e);}}
 private void saveFile(Uri uri,String path,String expected){jobs.execute(()->{javax.net.ssl.HttpsURLConnection c=null;boolean complete=false;try{if(!expected.equals(profile("kb")))throw new Exception("登录状态已改变，请重新选择文件。");c=api.open("kb",path,"GET",null,true);ApiClient.check(c);String type=c.getContentType();if(type==null||type.toLowerCase(Locale.ROOT).contains("text/html"))throw new Exception("服务器没有返回文件内容，已取消保存。");
  long expectedLength=c.getContentLengthLong(),count=0;try(InputStream in=c.getInputStream();OutputStream out=getContentResolver().openOutputStream(uri,"w")){if(out==null)throw new IOException("无法写入所选位置");byte[] buffer=new byte[65536];int n;while((n=in.read(buffer))!=-1){out.write(buffer,0,n);count+=n;}if(expectedLength>=0&&count!=expectedLength)throw new IOException("文件传输不完整");}complete=true;ui(()->notice("文件已保存到所选位置。"));
 }catch(Exception e){ui(()->error(e));}finally{if(c!=null)c.disconnect();if(!complete)try{android.provider.DocumentsContract.deleteDocument(getContentResolver(),uri);}catch(Exception ignored){ui(()->notice("保存失败，所选位置可能留下不完整文件，请检查并删除。"));}}});}
 private void pickText(){if(busy){notice("请先停止当前回答。");return;}new AlertDialog.Builder(this).setTitle("添加内容").setItems(new String[]{"选择文本文件（最多 256 KB）","查阅知识库文件"},(d,n)->{if(n==1){page="files";render();return;}Intent intent=new Intent(Intent.ACTION_OPEN_DOCUMENT);intent.addCategory(Intent.CATEGORY_OPENABLE);intent.setType("text/*");try{startActivityForResult(intent,PICK_TEXT);}catch(Exception e){notice("未找到文件选择器。");}}).setNegativeButton("取消",null).show();}
 private void voice(){if(busy){notice("请先停止当前回答。");return;}Intent intent=new Intent(RecognizerIntent.ACTION_RECOGNIZE_SPEECH);intent.putExtra(RecognizerIntent.EXTRA_LANGUAGE_MODEL,RecognizerIntent.LANGUAGE_MODEL_FREE_FORM);intent.putExtra(RecognizerIntent.EXTRA_LANGUAGE,"zh-CN");intent.putExtra(RecognizerIntent.EXTRA_PROMPT,"说出你的问题");try{startActivityForResult(intent,VOICE);}catch(Exception e){notice("手机未安装可用的语音识别服务。");}}
 @Override protected void onActivityResult(int request,int result,Intent data){super.onActivityResult(request,result,data);
  if(request==VPN_CONSENT){if(result==RESULT_OK)startFirewallService();else notice("未授予 VPN 授权，防火墙没有启用。");return;}
  if(request==SAVE_FILE){String path=downloadPath,expected=downloadProfile;downloadPath="";downloadProfile="";if(result==RESULT_OK&&data!=null&&data.getData()!=null&&!path.isEmpty())saveFile(data.getData(),path,expected);}
  if(result!=RESULT_OK||data==null)return;
  if(request==VOICE){ArrayList<String> words=data.getStringArrayListExtra(RecognizerIntent.EXTRA_RESULTS);if(words!=null&&!words.isEmpty()&&input!=null)input.setText(words.get(0));}
  if(request==PICK_TEXT&&data.getData()!=null){Uri uri=data.getData();jobs.execute(()->{try(InputStream in=getContentResolver().openInputStream(uri)){if(in==null)throw new IOException("无法读取文件");String content=new String(ApiClient.bytes(in,256*1024),"UTF-8");ui(()->{if(input!=null){input.append("\n\n[文本附件]\n"+content);notice("文本已加入输入栏，点击发送后才会提交到所选服务。");}});}catch(Exception e){ui(()->error(e));}});}
 }

 private void openFirewall(){if(busy){notice("请先停止当前回答再打开防火墙。");return;}page="firewall";render();}
 private void firewallBody(){
  ScrollView scroll=new ScrollView(this);LinearLayout content=col();content.setPadding(dp(20),dp(22),dp(20),dp(22));scroll.addView(content);body.addView(scroll,new LinearLayout.LayoutParams(-1,0,1));
  TextView title=label("掌握应用的联网权限",24);title.setTypeface(null,Typeface.BOLD);content.addView(title);
  TextView description=text("选择应用后，阻断它在 Wi-Fi 和移动网络上的全部联网。流量只在本机丢弃，不发送到外部 VPN 服务器。",15,0xff777777);description.setLineSpacing(dp(4),1);description.setPadding(0,dp(16),0,dp(20));content.addView(description);
  TextView state=label("",18),count=text("",13,0xff888888);pad(state,12);content.addView(state);content.addView(count);
  LinearLayout buttons=row();TextView start=pill("启用防火墙",true,()->enableFirewall()),stop=pill("停止",false,()->{stopService(new Intent(this,FirewallService.class));});buttons.addView(start,new LinearLayout.LayoutParams(0,dp(48),1));LinearLayout.LayoutParams st=new LinearLayout.LayoutParams(dp(90),dp(48));st.leftMargin=dp(12);buttons.addView(stop,st);content.addView(buttons);
  nav(content,"shield","选择要断网的应用",()->selectBlockedApps());nav(content,"settings","麦克风与隐私权限检查",()->privacySettings());nav(content,"link","Android VPN 设置",()->openSystem("android.settings.VPN_SETTINGS"));nav(content,"back","返回对话",()->{page="chat";render();});
  TextView scope=text("断网会影响所选应用的消息、广告和正常业务功能。一次只能运行一个 VPN；启用后可能替换你原来的 VPN。\n\n它不证明或检测偷听，也不能自动关闭其他应用的麦克风。请在系统隐私设置里检查权限和访问记录。\n\n若关闭防火墙、撤销 VPN 授权或系统停止服务，所选应用会恢复联网；本版不提供永久锁断网或开机自动保护。",13,0xff888888);scope.setLineSpacing(dp(4),1);scope.setPadding(0,dp(20),0,0);content.addView(scope);
  firewallHandler.removeCallbacksAndMessages(null);
  firewallHandler.post(new Runnable(){public void run(){if(destroyed||!page.equals("firewall"))return;state.setText(FirewallService.status);status.setText(FirewallService.running?"本地 VPN · 正在阻断":"防火墙未运行");try{JSONArray selected=new JSONArray(store.get("firewall_apps","[]"));count.setText("已选择 "+selected.length()+" 个应用 · 本次丢弃 "+FirewallService.packets.get()+" 个数据包（"+String.format(Locale.CHINA,"%.1f KB",FirewallService.bytes.get()/1024.0)+"）");}catch(Exception e){count.setText("规则读取失败");}start.setText(FirewallService.running?"已启用":"启用防火墙");stop.setEnabled(FirewallService.running);firewallHandler.postDelayed(this,1000);}});
 }
 private void enableFirewall(){try{
  JSONArray saved=new JSONArray(store.get("firewall_apps","[]"));ArrayList<String> packages=new ArrayList<>();for(int i=0;i<saved.length();i++)packages.add(saved.optString(i));BlockPolicy.requireNonEmpty(BlockPolicy.clean(packages,getPackageName()));
  Intent consent=android.net.VpnService.prepare(this);if(consent!=null)startActivityForResult(consent,VPN_CONSENT);else startFirewallService();
 }catch(Exception e){error(e);}}
 private void startFirewallService(){try{if(Build.VERSION.SDK_INT>=33&&checkSelfPermission("android.permission.POST_NOTIFICATIONS")!=android.content.pm.PackageManager.PERMISSION_GRANTED)requestPermissions(new String[]{"android.permission.POST_NOTIFICATIONS"},NOTIFY_CONSENT);startForegroundService(new Intent(this,FirewallService.class));}catch(Exception e){error(e);}}
 private void selectBlockedApps(){status.setText("正在读取本机应用列表…");jobs.execute(()->{try{
  android.content.pm.PackageManager manager=getPackageManager();List<android.content.pm.ApplicationInfo> installed=manager.getInstalledApplications(0);ArrayList<android.content.pm.ApplicationInfo> apps=new ArrayList<>();
  for(android.content.pm.ApplicationInfo app:installed)if(!app.packageName.equals(getPackageName())&&manager.checkPermission("android.permission.INTERNET",app.packageName)==android.content.pm.PackageManager.PERMISSION_GRANTED)apps.add(app);
  Collections.sort(apps,(a,b)->manager.getApplicationLabel(a).toString().compareToIgnoreCase(manager.getApplicationLabel(b).toString()));
  LinkedHashSet<String> selected=new LinkedHashSet<>();JSONArray saved=new JSONArray(store.get("firewall_apps","[]"));for(int i=0;i<saved.length();i++)selected.add(saved.getString(i));
  ui(()->{
   LinearLayout content=col();content.setPadding(dp(16),dp(8),dp(16),dp(8));EditText query=new EditText(this);query.setTextSize(15);query.setSingleLine(true);query.setHint("搜索应用名称或包名");content.addView(query);
   CheckBox system=new CheckBox(this);system.setText("显示系统应用（断网可能影响系统功能）");content.addView(system);
   TextView summary=text("勾选表示阻断联网。应用列表只在本机使用。",12,0xff777777);content.addView(summary);
   ListView list=new ListView(this);list.setChoiceMode(ListView.CHOICE_MODE_MULTIPLE);content.addView(list,new LinearLayout.LayoutParams(-1,dp(340)));
   ArrayList<android.content.pm.ApplicationInfo> visible=new ArrayList<>();
   Runnable refresh=()->{visible.clear();ArrayList<String> labels=new ArrayList<>();String filter=query.getText().toString().toLowerCase(Locale.ROOT);for(android.content.pm.ApplicationInfo app:apps){boolean isSystem=(app.flags&android.content.pm.ApplicationInfo.FLAG_SYSTEM)!=0;if(isSystem&&!system.isChecked()&&!selected.contains(app.packageName))continue;String name=manager.getApplicationLabel(app).toString();if(!(name+" "+app.packageName).toLowerCase(Locale.ROOT).contains(filter))continue;visible.add(app);labels.add(name+(isSystem?"（系统）":"")+"\n"+app.packageName);}
    list.setAdapter(new ArrayAdapter<>(this,android.R.layout.simple_list_item_multiple_choice,labels));for(int i=0;i<visible.size();i++)list.setItemChecked(i,selected.contains(visible.get(i).packageName));summary.setText("已选择 "+selected.size()+" 个应用。列表不会上传。");};
   list.setOnItemClickListener((parent,v,n,id)->{String pkg=visible.get(n).packageName;if(list.isItemChecked(n))selected.add(pkg);else selected.remove(pkg);summary.setText("已选择 "+selected.size()+" 个应用。列表不会上传。");});
   query.addTextChangedListener(new android.text.TextWatcher(){public void beforeTextChanged(CharSequence s,int start,int count,int after){}public void onTextChanged(CharSequence s,int start,int before,int count){refresh.run();}public void afterTextChanged(android.text.Editable s){}});system.setOnCheckedChangeListener((v,on)->refresh.run());refresh.run();
   new AlertDialog.Builder(this).setTitle("选择断网应用").setView(content).setPositiveButton(FirewallService.running?"保存并应用":"保存规则",(d,w)->{try{List<String> policy=BlockPolicy.clean(selected,getPackageName());store.put("firewall_apps",new JSONArray(policy).toString());if(FirewallService.running){if(policy.isEmpty())stopService(new Intent(this,FirewallService.class));else startForegroundService(new Intent(this,FirewallService.class).setAction("APPLY"));}status.setText("断网规则已保存");}catch(Exception e){error(e);}}).setNegativeButton("取消",null).show();
  });
 }catch(Exception e){ui(()->error(e));}});}
 private void privacySettings(){new AlertDialog.Builder(this).setTitle("检查麦克风和隐私权限").setMessage("在系统设置中查看哪些应用最近访问麦克风；对不需要录音的应用关闭麦克风权限。防火墙无法替你修改其他应用的权限。不同手机的设置路径可能不同。").setPositiveButton("打开隐私设置",(d,w)->openSystem("android.settings.PRIVACY_SETTINGS")).setNeutralButton("查看应用权限",(d,w)->openSystem("android.settings.MANAGE_APPLICATIONS_SETTINGS")).setNegativeButton("关闭",null).show();}
 private void openSystem(String action){try{startActivity(new Intent(action));}catch(Exception e){try{startActivity(new Intent(android.provider.Settings.ACTION_SETTINGS));}catch(Exception ignored){notice("请手动打开系统设置。");}}}
 @Override protected void onNewIntent(Intent intent){super.onNewIntent(intent);setIntent(intent);if(intent.getBooleanExtra("open_firewall",false))openFirewall();}
 @Override public void onBackPressed(){if(drawer!=null)closeDrawer();else if(!page.equals("chat")){page="chat";render();}else if(busy)new AlertDialog.Builder(this).setMessage("正在接收回答，是否停止？").setPositiveButton("停止",(d,w)->stopChat()).setNegativeButton("继续",null).show();else super.onBackPressed();}
 @Override protected void onDestroy(){destroyed=true;firewallHandler.removeCallbacksAndMessages(null);if(api!=null)api.cancel();jobs.shutdownNow();thumbnails.shutdownNow();thumbnailCache.evictAll();if(tts!=null){tts.stop();tts.shutdown();}super.onDestroy();}
}
